# Generated by Django 4.2.10 on 2025-07-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallimall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
