# Generated by Django 4.2.10 on 2026-05-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallimall_app', '0002_alter_cart_cart_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
