# Generated by Django 4.2.10 on 2026-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallimall_app', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartsuggestion',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
